### ISSUE TITLE
Multiple search terms in one line

### ISSUE THREAD

**Issue by shawnthomas20** [shelbyt/searchMatch#1]
![not catching multiple search terms](https://user-images.githubusercontent.com/20155867/79146754-b3d6cb00-7d77-11ea-983d-419dc736eb3b.JPG)

seems to catch the same term in one line, but not two different terms in one line related to a single key (e.g. will catch SOB twice, but not SOB and short)

**Comment by shawnthomas20** [comment]
this would be bad:
sdafioehalsdjflkaj positive resp dist respdsalk;fj dkfhelthladfjoiasdfheirf negative for sob

would fool people into thinking there was no shortness of breath, but inside the text it identified "positive resp dist" = respiratory distress

**Comment by shelbyt** [comment]
Fixed by https://github.com/shelbyt/searchMatch/commit/cc162945edb21de018bdbff94292e56c515a008f
