### ISSUE TITLE
date handler getting thrown off by "bad dates"

### ISSUE THREAD

**Issue by shawnthomas20** [shelbyt/searchMatch#2]
179/40 

Basically, blood pressures are throwing off the date thing. Any way to just throw that type of error?

**Comment by shelbyt** [comment]
Will fix by adding this range in the dates in the datefinder library:

![image](https://user-images.githubusercontent.com/1332316/79167858-4e95d080-7d9d-11ea-96d8-9effae0e6251.png)


![image](https://user-images.githubusercontent.com/1332316/79167982-a03e5b00-7d9d-11ea-8781-faa8b8959f53.png)
